name: Build debug

on:
  pull_request:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
      - 'version_map.json'
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository_owner != 'FCL-Team' || github.event_name == 'pull_request' }}
    name: Build for ${{matrix.arch}}
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew assemblefordebug -Darch=${{ matrix.arch }} --no-daemon

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-${{matrix.arch}}
          path: FCL/build/outputs/apk/fordebug/*
